// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijokqexxjlhjobwiwkfq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlqb2txZXh4amxoam9id2l3a2ZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxODcxODIsImV4cCI6MjA1Mzc2MzE4Mn0.73ICJo7e9eC0HPwkN7CnBNsnWCqkRjS8ndwjUePSiMo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);